image: python:3.8

pipelines:
  default:
    - step:
        name: Code style
        script:
          - pip install flake8
          - flake8 . --config .flake8 --show-source --statistics
    - step:
        name: Run Tests
        caches:
          - pip
        script:
          - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - pip install pytest
          - pytest -v Tests/* --junitxml=test-reports/report.xml
