# Backend Flask config
HOST = '127.0.0.1'
PORT = 7654

# vkontakte
VK_APP_VERSION = 5.126
VK_APP_ID = 12345678
VK_APP_SECRET_KEY = ''
VK_APP_SERVICE_KEY = ''
VK_APP_ACCESS_TOKEN = ''

# facebook
FB_APP_VERSION = 9.0
FB_APP_ID = 123456789123456789
FB_CLIENT_MARKER = ''
FB_APP_SECRET_KEY = ''
FB_APP_ACCESS_KEY = ''

# twitter
TW_CONSUMER_KEY = ''
TW_CONSUMER_SECRET = ''
TW_ACCESS_TOKEN_KEY = ''
TW_ACCESS_TOKEN_SECRET = ''

# linkedin
LI_USERNAME = ''
LI_PASSWORD = ''

# mymail.ru
MM_APP_ID = 123456
MM_PASSWORD = ''
MM_USERNAME = ''
MM_APP_SECRET_KEY = ''
MM_APP_PRIVATE_KEY = ''

# Emailrep.io
EMAILREP_API_KEY = ''

# Dehashed.com
DEHASHED_API_KEY = ''
